### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pikurasa** [arzynik/cheryl#30]
Hi,

Is this a proprietary license?

If not, please specify the license at the top.

Thanks!

**Comment by pikurasa** [comment]
Hurrah! You licensed the work as MIT license! Thank you so much!!!

Look forward to further development. (In the interim, I am using OwnCloud for online file sharing, but I do like the layout of your work. I also **really** like the search engine. If there could also be anonymous [no log-in] search and download [read-only] I would super-happy!)

**Comment by arzynik** [comment]
@pikurasa got it. i believe thats what you intended for #33. hopefully i can get to this soon. and glad you like it!

**Comment by pikurasa** [comment]
Yes, that is what I intended for #33. Design is cool, name is cool, it just feels pretty all-around cool.
