### ISSUE TITLE
Not working on local install

### ISSUE THREAD

**Issue by 20Fourteen** [arzynik/cheryl#47]
Using XAMPP, cannot get this to work.

Firstly the slash had to be removed for `cheryl.css` and `cheryl.js` in the **`cheryl.phtml`** file.

But then I get this in the console.

![sshot-48](https://cloud.githubusercontent.com/assets/8763290/15784165/3d94aeba-29a9-11e6-88d2-3e3657b6c231.png)

Any ideas?

**Comment by arzynik** [comment]
@20Fourteen the issue was it being served from a subdirectory instead of from base. ive fixed the issue in https://github.com/arzynik/cheryl/releases/tag/v4.0.1.

**Comment by 20Fourteen** [comment]
I'm unable to login with the default credentials, and changing them did not help.

The only errors I see are `PHP Warning:  array_merge(): Argument #2 is not an array in X:\xampp\htdocs\w\cheryl\src\Cheryl.php on line 87
`
